<?php

namespace Database\Seeders;

use App\Models\CentroCostoCatalogo;
use App\Models\Empresa;
use Illuminate\Database\Seeder;

class CentrosCostoCatalogoSeeder extends Seeder
{
    /**
     * NOTA: "S&M HUGHES" y "S&M TIGO" se fusionaron en una sola empresa ("S&M TIGO"), cuyos
     * centros de costo ahora se distinguen por la columna `proyecto` (hughesnet, Tigo Express,
     * Tigo Home, Tigo Tropas, Nacional Express, Nacional Home, HOME, Hospital). Dos códigos
     * venían duplicados en la lista fuente con datos distintos y se resolvieron quedándose con
     * la primera ocurrencia: 221205 (TOLU, no SUCRE) y 220804 (SAN GIL, no FLORIDABLANCA).
     */
    private const FILAS = [
        // empresa, codigo, nombre, ciudad, proyecto
        ['CYC', '000001', 'ADMINISTRACION (CYC)', 'PEREIRA', null],

        ['S&M TIGO', '060302', 'COMERCIAL', 'APARTADO', 'hughesnet'],
        ['S&M TIGO', '0603031', 'OPERACIÓN', 'APARTADO', 'hughesnet'],
        ['S&M TIGO', '220603', 'TIGO EXPRESS APARTADO CLL 98 99-63 FUNDADORES', 'APARTADO', 'Tigo Express'],
        ['S&M TIGO', '220202', 'TIGO EXPRESS ARMENIA CR 14 FUNDADORES', 'ARMENIA', 'Tigo Express'],
        ['S&M TIGO', '220203', 'TIGO EXPRESS ARMENIA CLL 18 15 43', 'ARMENIA', 'Tigo Express'],
        ['S&M TIGO', '220902', 'TIGO EXPRESS BARANOA CRA 19 17-28 PLAZA CENTRO', 'BARANOA', 'Tigo Express'],
        ['S&M TIGO', '220802', 'TIGO EXPRESS BARRANCABERMEJA (CR 8 N 6 10 LC 113 CC CITY)', 'BARRANCABERMEJA', 'Tigo Express'],
        ['S&M TIGO', '090102', 'COMERCIAL', 'BARRANQUILLA', 'hughesnet'],
        ['S&M TIGO', '0901031', 'OPERACIÓN', 'BARRANQUILLA', 'hughesnet'],
        ['S&M TIGO', '220990', 'TIGO HOME BARRANQUILLA', 'BARRANQUILLA', 'Tigo Home'],
        ['S&M TIGO', '220904', 'TIGO EXPRESS SOLEDAD CLL 20 19-02', 'SOLEDAD', 'Tigo Express'],
        ['S&M TIGO', '070102', 'COMERCIAL', 'BOGOTA', 'hughesnet'],
        ['S&M TIGO', '0701031', 'OPERACIÓN', 'BOGOTA', 'hughesnet'],
        ['S&M TIGO', '220707', 'TIGO EXPRESS BOGOTA BOSA BRASIL', 'BOGOTA', 'Tigo Express'],
        ['S&M TIGO', '220717', 'TIGO EXPRESS BOGOTA VENECIA', 'BOGOTA', 'Tigo Express'],
        ['S&M TIGO', '220790', 'TIGO HOME BOGOTA', 'BOGOTA', 'HOME'],
        ['S&M TIGO', '220718', 'TIGO EXPRESS BOGOTA AV CR 80 KENNEDY ROMA', 'BOGOTA', 'Tigo Express'],
        ['S&M TIGO', '220706', 'TIGO EXPRESS BOGOTA CLL 163A SAN CRISTOBAL', 'BOGOTA', 'Tigo Express'],
        ['S&M TIGO', '220719', 'TIGO EXPRESS SOACHA CLL 15 LAS VILLAS', 'SOACHA', 'Tigo Express'],
        ['S&M TIGO', '220716', 'TIGO EXPRESS BOGOTA CL 37 SUR CENTRO KENNEDY', 'BOGOTA', 'Tigo Express'],
        ['S&M TIGO', '220757', 'TIGO EXPRESS BOGOTA 61B-08 SAN FRANCISCO', 'BOGOTA', 'Tigo Express'],
        ['S&M TIGO', '220768', 'TIGO EXPRESS BOGOTA CLL 64 ENGATIVA', 'BOGOTA', 'Tigo Express'],
        ['S&M TIGO', '220720', 'TIGO EXPRESS BOGOTA SANTA LIBRADA', 'BOGOTA', 'Tigo Express'],
        ['S&M TIGO', '080102', 'COMERCIAL', 'BUCARAMANGA', 'hughesnet'],
        ['S&M TIGO', '0801031', 'OPERACIÓN', 'BUCARAMANGA', 'hughesnet'],
        ['S&M TIGO', '220801', 'TIGO EXPRESS BUCARAMANGA CABECERA', 'BUCARAMANGA', 'Tigo Express'],
        ['S&M TIGO', '220811', 'TIGO EXPRESS BUCARAMANGA CENTRO', 'BUCARAMANGA', 'Tigo Express'],
        ['S&M TIGO', '030102', 'COMERCIAL', 'CALI', 'hughesnet'],
        ['S&M TIGO', '0301031', 'OPERACIÓN', 'CALI', 'hughesnet'],
        ['S&M TIGO', '220302', 'TIGO EXPRESS CALI CR 4 14', 'CALI', 'Tigo Express'],
        ['S&M TIGO', '220306', 'TIGO ÉXITO CALI SAN FERNANDO', 'CALI', 'Tigo Express'],
        ['S&M TIGO', '220330', 'TIGO TROPAS CALI', 'CALI', 'Tigo Tropas'],
        ['S&M TIGO', '220307', 'TIGO EXPRESS CALI LC 9 LA CASCADA', 'CALI', 'Tigo Express'],
        ['S&M TIGO', '220308', 'TIGO EXPRESS CALI CL 12 PLAZA DE CAICEDO', 'CALI', 'Tigo Express'],
        ['S&M TIGO', '220309', 'TIGO EXPRESS CALI SILOE', 'CALI', 'Tigo Express'],
        ['S&M TIGO', '100102', 'COMERCIAL', 'CARTAGENA', 'hughesnet'],
        ['S&M TIGO', '1001031', 'OPERACIÓN', 'CARTAGENA', 'hughesnet'],
        ['S&M TIGO', '221090', 'TIGO HOME CARTAGENA', 'CARTAGENA', 'HOME'],
        ['S&M TIGO', '221002', 'TIGO EXPRESS CARTAGENA BAZURTO 27A-26', 'CARTAGENA', 'Tigo Express'],
        ['S&M TIGO', '221001', 'TIGO EXPRESS CARTAGENA LOS EJECUTIVOS LC 37', 'CARTAGENA', 'Tigo Express'],
        ['S&M TIGO', '220311', 'TIGO EXPRESS CARTAGO CRA 12 5-106 CENTRO', 'CARTAGO', 'Tigo Express'],
        ['S&M TIGO', '220504', 'TIGO EXPRESS CHINCHINA CLL 12 8-12', 'CHINCHINA', 'Tigo Express'],
        ['S&M TIGO', '150102', 'COMERCIAL', 'CUCUTA', 'hughesnet'],
        ['S&M TIGO', '1501031', 'OPERACIÓN', 'CUCUTA', 'hughesnet'],
        ['S&M TIGO', '221501', 'TIGO EXPRESS CUCUTA CLL 10 1-11 LA PLAYA', 'CUCUTA', 'Tigo Express'],
        ['S&M TIGO', '221503', 'TIGO EXPRESS CUCUTA AV 8 7-89 CENTRO', 'CUCUTA', 'Tigo Express'],
        ['S&M TIGO', '221502', 'TIGO EXPRESS CUCUTA AV 3 9-70', 'CUCUTA', 'Tigo Express'],
        ['S&M TIGO', '220747', 'TIGO ESPRESS MADRID CRA 7 7-51', 'MADRID', 'Tigo Express'],
        ['S&M TIGO', '220727', 'TIGO EXPRESS FACATATIVA CALLE 5 NRO 2-74 CENTRO', 'FACATATIVA', 'Tigo Express'],
        ['S&M TIGO', '220803', 'TIGO EXPRESS FLORIDABLANCA CLL 5 PLAZA CENTRAL', 'FLORIDABLANCA', 'Tigo Express'],
        ['S&M TIGO', '220805', 'TIGO EXPRESS FLORIDABLANCA 6AE-80 BR LA CUMBRE', 'FLORIDABLANCA', 'Tigo Express'],
        ['S&M TIGO', '220737', 'TIGO EXPRESS FUSAGASUGA KR 5 9-45', 'FUSAGAZUGA', 'Tigo Express'],
        ['S&M TIGO', '220791', 'TIGO HOME FUSAGASUGA', 'FUSAGAZUGA', 'Tigo Home'],
        ['S&M TIGO', '220903', 'TIGO EXPRESS GALAPA CLL 10 21-53 CENTRO', 'GALAPA', 'Tigo Express'],
        ['S&M TIGO', '220610', 'TIGO EXPRESS GUARNE CRA 51 51-12', 'GUARNE', 'Tigo Express'],
        ['S&M TIGO', '040102', 'COMERCIAL', 'IBAGUE', 'hughesnet'],
        ['S&M TIGO', '0401031', 'OPERACIÓN', 'IBAGUE', 'hughesnet'],
        ['S&M TIGO', '220702', 'TIGO EXPRESS ITAGUI 02 CR 58 D CENTRO DE LA MODA', 'ITAGUI', 'Tigo Express'],
        ['S&M TIGO', '220605', 'TIGO EXPRESS ITAGUI CENTRO COMERCIAL CL 50 48', 'ITAGUI', 'Tigo Express'],
        ['S&M TIGO', '220304', 'TIGO EXPRESS JAMUNDI CRA 10', 'JAMUNDI', 'Tigo Express'],
        ['S&M TIGO', '220604', 'TIGO EXPRESS LA CEJA CLL 19 19-103', 'LA CEJA', 'Tigo Express'],
        ['S&M TIGO', '220120', 'TIGO EXPRESS LA VIRGINIA CR 8 7 23 CENTRO', 'LA VIRGINIA', 'Tigo Express'],
        ['S&M TIGO', '220905', 'TIGO EXPRESS MALAMBO CLL 10 12 16 CENTRO', 'MALAMBO', 'Tigo Express'],
        ['S&M TIGO', '220503', 'TIGO EXPRESS MANIZALES CLL 18 23-04 ESQUINA', 'MANIZALES', 'Tigo Express'],
        ['S&M TIGO', '220502', 'TIGO EXPRESS MANIZALES CR 23 #26-27', 'MANIZALES', 'Tigo Express'],
        ['S&M TIGO', '220609', 'TIGO EXPRESS MARINILLA CR 30 32-09 ESQUINA PARQUE', 'MARINILLA', 'Tigo Express'],
        ['S&M TIGO', '060102', 'COMERCIAL', 'MEDELLIN', 'hughesnet'],
        ['S&M TIGO', '0601031', 'OPERACIÓN', 'MEDELLIN', 'hughesnet'],
        ['S&M TIGO', '220601', 'TIGO EXPRESS MEDELLIN 01 LAS AMERICAS', 'MEDELLIN', 'Tigo Express'],
        ['S&M TIGO', '220602', 'TIGO EXPRESS MEDELLIN 02 BELEN', 'MEDELLIN', 'Tigo Express'],
        ['S&M TIGO', '220608', 'TIGO EXPRESS CALDAS ANTIOQUIA', 'CALDAS', 'Tigo Express'],
        ['S&M TIGO', '220690', 'TIGO HOME MEDELLIN', 'MEDELLIN', 'HOME'],
        ['S&M TIGO', '120102', 'COMERCIAL', 'MONTERIA', 'hughesnet'],


        ['S&M TIGO', '1201031', 'OPERACIÓN', 'MONTERIA', 'hughesnet'],
        ['S&M TIGO', '221201', 'TIGO HOME MONTERIA', 'MONTERIA', 'HOME'],
        ['S&M TIGO', '222102', 'TIGO EXPRESS NACIONAL', 'NACIONAL EXPRESS', 'Nacional Express'],
        ['S&M TIGO', '222190', 'TIGO NACIONAL HOME', 'NACIONAL HOME', 'Nacional Home'],
        ['S&M TIGO', '220305', 'TIGO EXPRESS PALMIRA CC UNICENTRO', 'PALMIRA', 'Tigo Express'],
        ['S&M TIGO', '110102', 'COMERCIAL', 'PASTO', 'hughesnet'],
        ['S&M TIGO', '1101031', 'OPERACIÓN', 'PASTO', 'hughesnet'],
        ['S&M TIGO', '000001', 'ADMINISTRACION CENTRAL', 'PEREIRA', 'hughesnet'],
        ['S&M TIGO', '000003', 'CALL CENTER', 'PEREIRA', 'Hospital'],
        ['S&M TIGO', '010102', 'COMERCIAL', 'PEREIRA', 'hughesnet'],
        ['S&M TIGO', '0101031', 'OPERACIÓN', 'PEREIRA', 'hughesnet'],
        ['S&M TIGO', '210102', 'COMERCIAL NACIONAL', 'PEREIRA', 'hughesnet'],
        ['S&M TIGO', '2101031', 'OPERACIÓN NACIONAL', 'PEREIRA', 'hughesnet'],
        ['S&M TIGO', '220102', 'TIGO EXPRESS PEREIRA CALLE 19 CON 8', 'PEREIRA', 'Tigo Express'],
        ['S&M TIGO', '220103', 'TIGO EXPRESS PEREIRA EXITO CUBA', 'PEREIRA', 'Tigo Express'],
        ['S&M TIGO', '220190', 'TIGO HOME PEREIRA', 'PEREIRA', 'HOME'],
        ['S&M TIGO', '220104', 'TIGO EXPRESS PEREIRA CL 25 PARQUE EL LAGO', 'PEREIRA', 'Tigo Express'],
        ['S&M TIGO', '160102', 'COMERCIAL', 'POPAYAN', 'hughesnet'],
        ['S&M TIGO', '1601031', 'OPERACIÓN', 'POPAYAN', 'hughesnet'],
        ['S&M TIGO', '060202', 'COMERCIAL', 'RIONEGRO', 'hughesnet'],
        ['S&M TIGO', '0602031', 'OPERACIÓN', 'RIONEGRO', 'hughesnet'],
        ['S&M TIGO', '220611', 'TIGO EXPRESS RIONEGRO CLL 51 48-52', 'RIONEGRO', 'Tigo Express'],
        ['S&M TIGO', '220804', 'TIGO EXPRESS SAN GIL CRA 10 14-18', 'SAN GIL', 'Tigo Express'],
        ['S&M TIGO', '130102', 'COMERCIAL', 'SANTA MARTA', 'hughesnet'],
        ['S&M TIGO', '1301031', 'OPERACIÓN', 'SANTA MARTA', 'hughesnet'],
        ['S&M TIGO', '220160', 'TIGO EXPRESS SANTA ROSA DE CABAL CLL 14', 'SANTA ROSA DE CABAL', 'Tigo Express'],
        ['S&M TIGO', '221202', 'TIGO HOME SINCELEJO', 'SINCELEJO', 'HOME'],
        ['S&M TIGO', '221203', 'TIGO EXPRESS SINCELEJO CLL 20 20 63 CENTRO', 'SINCELEJO', 'Tigo Express'],
        ['S&M TIGO', '221205', 'TIGO EXPRESS TOLU CRA 3 N 14 35', 'TOLU', 'Tigo Express'],
        ['S&M TIGO', '030202', 'COMERCIAL', 'TULUA', 'hughesnet'],
        ['S&M TIGO', '0302031', 'OPERACIÓN', 'TULUA', 'hughesnet'],
        ['S&M TIGO', '140102', 'COMERCIAL', 'TUNJA', 'hughesnet'],
        ['S&M TIGO', '1401031', 'OPERACIÓN', 'TUNJA', 'hughesnet'],
        ['S&M TIGO', '221901', 'TIGO EXPRESS VALLEDUPAR CRA 7 16A-78 LC 2', 'VALLEDUPAR', 'Tigo Express'],
        ['S&M TIGO', '221903', 'TIGO HOME VALLEDUPAR', 'VALLEDUPAR', 'Tigo Home'],
        ['S&M TIGO', '220813', 'TIGO EXPRESS VILLA DEL ROSARIO CRA 8 5-15', 'VILLA DEL ROSARIO', 'Tigo Express'],
        ['S&M TIGO', '070202', 'COMERCIAL', 'VILLAVICENCIO', 'hughesnet'],
        ['S&M TIGO', '0702031', 'OPERACIÓN', 'VILLAVICENCIO', 'hughesnet'],
        ['S&M TIGO', '2211204', 'TIGO EXPRESS CERETE 13 14-09 LOS ALMENDROS', 'CERETE', 'Tigo Express'],
        ['S&M TIGO', '221003', 'TIGO CARTAGENA AV VENEZUELA 1A 42', 'CARTAGENA', 'Tigo Express'],
        ['S&M TIGO', '220906', 'TIGO EXPRESS BARRANQUILLA LC 11B CC JARDIN DEL RIO', 'BARRANQUILLA', 'Tigo Express'],
        ['S&M TIGO', '220806', 'TIGO EXPRESS CAJICA CRA 5 1-98', 'CAJICA', 'Tigo Express'],
        ['S&M TIGO', '220606', 'TIGO EXPRESS BELLO CLL 49 50-10', 'BELLO', 'Tigo Express'],
        ['S&M TIGO', '220607', 'TIGO VILLA MARIA -CALDAS CR5 17 13', 'VILLA MARIA', 'Tigo Express'],
        ['S&M TIGO', '220612', 'TIGO SAN ANTONIO DE PRADO', 'MEDELLIN', 'Tigo Express'],
        ['S&M TIGO', '220708', 'TIGO EXPRESS BOGOTA AC 145 103B-80 SUBA', 'BOGOTA', 'Tigo Express'],
        ['S&M TIGO', '220907', 'TIGO EXPRESS LA PAZ CR 13 99D 07', 'BARRANQUILLA', 'Tigo Express'],
        ['S&M TIGO', '221004', 'TIGO EXPRESS ARJONA 51 48 CLL DEL COCO', 'CARTAGENA', 'Tigo Express'],
        ['S&M TIGO', '220704', 'TIGO EXPRESS BOGOTA CRA 18 21 05 RESTREPO', 'BOGOTA', 'Tigo Express'],
        ['S&M TIGO', '220703', 'REG CENTRO TIGO EXPRESS FDV', 'BOGOTA', 'Tigo Express'],
        ['S&M TIGO', '220769', 'TIGO ORIENTE PDV', 'CUCUTA', 'Tigo Express'],
        ['SERVIMERCADEO', '020101', 'ADMINISTRACION', 'ARMENIA', null],
        ['SERVIMERCADEO', '020102', 'COMERCIAL', 'ARMENIA', null],
        ['SERVIMERCADEO', '0201031', 'OPERACIONES', 'ARMENIA', null],
        ['SERVIMERCADEO', '080201', 'ADMINISTRACION', 'BARRANCABERMEJA', null],
        ['SERVIMERCADEO', '080202', 'COMERCIAL', 'BARRANCABERMEJA', null],
        ['SERVIMERCADEO', '0802031', 'OPERACIONES', 'BARRANCABERMEJA', null],
        ['SERVIMERCADEO', '090101', 'ADMINISTRACION', 'BARRANQUILLA', null],
        ['SERVIMERCADEO', '090102', 'COMERCIAL', 'BARRANQUILLA', null],
        ['SERVIMERCADEO', '0901031', 'OPERACIONES', 'BARRANQUILLA', null],
        ['SERVIMERCADEO', '0901101', 'MEDIA COMER', 'BARRANQUILLA', null],
        ['SERVIMERCADEO', '070101', 'ADMINISTRACION', 'BOGOTA D.C.', null],
        ['SERVIMERCADEO', '070102', 'COMERCIAL', 'BOGOTA D.C.', null],
        ['SERVIMERCADEO', '0701031', 'OPERACIONES', 'BOGOTA D.C.', null],
        ['SERVIMERCADEO', '080101', 'ADMINISTRACION', 'BUCARAMANGA', null],
        ['SERVIMERCADEO', '080102', 'COMERCIAL', 'BUCARAMANGA', null],
        ['SERVIMERCADEO', '0801031', 'OPERACIONES', 'BUCARAMANGA', null],
        ['SERVIMERCADEO', '030101', 'ADMINISTRACION', 'CALI', null],
        ['SERVIMERCADEO', '030102', 'COMERCIAL', 'CALI', null],
        ['SERVIMERCADEO', '0301031', 'OPERACIONES', 'CALI', null],
        ['SERVIMERCADEO', '150101', 'ADMINISTRACION', 'CUCUTA', null],
        ['SERVIMERCADEO', '150102', 'COMERCIAL', 'CUCUTA', null],
        ['SERVIMERCADEO', '1501031', 'OPERACIONES', 'CUCUTA', null],
        ['SERVIMERCADEO', '050101', 'ADMINISTRACION', 'MANIZALES', null],
        ['SERVIMERCADEO', '050102', 'COMERCIAL', 'MANIZALES', null],
        ['SERVIMERCADEO', '0501031', 'OPERACIONES', 'MANIZALES', null],
        ['SERVIMERCADEO', '060101', 'ADMINISTRACION', 'MEDELLIN', null],
        ['SERVIMERCADEO', '060102', 'COMERCIAL', 'MEDELLIN', null],
        ['SERVIMERCADEO', '0601031', 'OPERACIONES', 'MEDELLIN', null],
        ['SERVIMERCADEO', '060108', 'PROYECTO BALCOLDEX', 'MEDELLIN', null],
        ['SERVIMERCADEO', '120101', 'ADMINISTRACION', 'MONTERIA', null],
        ['SERVIMERCADEO', '120102', 'COMERCIAL', 'MONTERIA', null],
        ['SERVIMERCADEO', '1201031', 'OPERACIONES', 'MONTERIA', null],
        ['SERVIMERCADEO', '110101', 'ADMINISTRACION', 'PASTO', null],
        ['SERVIMERCADEO', '110102', 'COMERCIAL', 'PASTO', null],
        ['SERVIMERCADEO', '1101031', 'OPERACIONES', 'PASTO', null],
        ['SERVIMERCADEO', '0001', 'GERENCIA', 'PEREIRA', null],
        ['SERVIMERCADEO', '0005', 'ASESORIAS', 'PEREIRA', null],
        ['SERVIMERCADEO', '010102', 'COMERCIAL', 'PEREIRA', null],
        ['SERVIMERCADEO', '0101031', 'OPERACIONES', 'PEREIRA', null],
        ['SERVIMERCADEO', '2101031', 'NACIONAL OPERATIVO', 'PEREIRA', null],
        ['SERVIMERCADEO', '210102', 'NACIONAL COMERCIAL', 'PEREIRA', null],
        ['SERVIMERCADEO', '010107', 'OPERACIONES IGT PEREIRA', 'PEREIRA', null],
        ['SERVIMERCADEO', '00010', 'CALL CENTER COLOMBIA', 'PEREIRA', null],
        ['SERVIMERCADEO', '160101', 'ADMINISTRACION', 'POPAYAN', null],
        ['SERVIMERCADEO', '160102', 'COMERCIAL', 'POPAYAN', null],
        ['SERVIMERCADEO', '1601031', 'OPERACIONES', 'POPAYAN', null],
        ['SERVIMERCADEO', '060201', 'ADMINISTRACION', 'RIONEGRO', null],
        ['SERVIMERCADEO', '060202', 'COMERCIAL', 'RIONEGRO', null],
        ['SERVIMERCADEO', '0602031', 'OPERACIONES', 'RIONEGRO', null],
    ];

    private const EMPRESA_MAP = [
        'CYC'           => 'Servicios y Mercadeo COL',
        'S&M TIGO'      => 'Servicios y Mercadeo COL',
        'SERVIMERCADEO' => 'Servimercadeo COL',
    ];

    public function run(): void
    {
        $empresaIds = Empresa::whereIn('nombre', array_unique(self::EMPRESA_MAP))->pluck('id', 'nombre');

        foreach (self::FILAS as [$empresa, $codigo, $nombre, $ciudad, $proyecto]) {
            $empresaId = $empresaIds[self::EMPRESA_MAP[$empresa]] ?? null;

            CentroCostoCatalogo::updateOrCreate(
                ['empresa_id' => $empresaId, 'codigo' => $codigo],
                ['nombre' => $nombre, 'ciudad' => $ciudad, 'proyecto' => $proyecto, 'activo' => true]
            );
        }
    }
}
