<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use App\Models\Empresa;

class EmpleadosSeeder extends Seeder
{
    public function run(): void
    {
        $empServMercadeo  = Empresa::where('nombre', 'Servicios y Mercadeo COL')->value('id');
        $empServimercadeo = Empresa::where('nombre', 'Servimercadeo COL')->value('id');

        $empleados = [
            [
                'name'     => 'Juan Camilo Marin Zapata',
                'email'    => 'marin.jc2005@gmail.com',
                'password' => '$2y$12$.IBwM/iM2Im2jgFXzQfqHO5Sq5Z/X.vczt1SXo1Shap1.IeSMNMk.',
                'rol'      => 'administrador',
                'activo'   => true,
                'cedula'              => '1089381135',
                'apellidos'           => 'Marin Zapata',
                'nombres'             => 'Juan Camilo',
                'sede'                => 'Pereira',
                'fecha_nacimiento'    => '2005-10-23',
                'lugar_nacimiento'    => 'Pereira',
                'raza'                => 'Mestizo',
                'genero'              => 'Masculino',
                'estado_civil'        => 'Casado/a',
                'nivel_escolaridad'   => 'Tecnólogo',
                'direccion_residencia'=> 'Terra Grata Condominio',
                'movil'               => '3233294494',
                'estrato'             => '3',
                'barrio'              => 'Las Violetas',
                'numero_hijos'        => null,
                'ingresos'            => 2500000,
                'observaciones_medicas' => 'Sin observaciones',
                'alergias'            => 'Ninguna',
                'rh'               => 'O+',
                'eps'              => 'SURA EPS',
                'arl'              => 'SURA',
                'fondo_pensiones'  => 'PROTECCION',
                'caja_compensacion'=> 'COMFAMA',
                'licencia_carro'       => null,
                'licencia_carro_vence' => null,
                'licencia_moto'        => null,
                'licencia_moto_vence'  => null,
                'tiene_cert_alturas'   => true,
                'cert_alturas_vence'   => '2026-11-20',
                'estado_empleado' => 'Activo',
                'codigo_directv'  => 'DTV-001',
                'empresa_id'      => $empServMercadeo,
                'comentarios'     => 'Administrador del sistema.',
                'cargo'            => 'AUXILIAR DE SISTEMAS',
                'tipo_funcionario' => 'TÉCNICO',
                'tipo_vinculacion' => 'Empleado directo',
                'cuenta_bancaria'  => '123456789012',
                'tipo_cuenta'      => 'Ahorros',
                'banco'            => 'BANCOLOMBIA',
                'contacto_emergencia_nombre'     => 'María González',
                'contacto_emergencia_telefono'   => '3009876543',
                'contacto_emergencia_parentesco' => 'Madre',
            ],
            [
                'name'     => 'Simon Gallego Morales',
                'email'    => 'simon.gallego@empresa.com',
                'password' => Hash::make('Password123'),
                'rol'      => 'consultor',
                'activo'   => true,
                'cedula'              => '1098765432',
                'apellidos'           => 'Gallego Morales',
                'nombres'             => 'Simon',
                'sede'                => 'Medellín',
                'fecha_nacimiento'    => '1995-06-14',
                'lugar_nacimiento'    => 'Medellín',
                'raza'                => 'Mestizo',
                'genero'              => 'Masculino',
                'estado_civil'        => 'Soltero/a',
                'nivel_escolaridad'   => 'Profesional',
                'direccion_residencia'=> 'Calle 50 # 30-20, Laureles',
                'movil'               => '3104567890',
                'estrato'             => '4',
                'barrio'              => 'Laureles',
                'numero_hijos'        => 0,
                'ingresos'            => 3200000,
                'observaciones_medicas' => 'Sin observaciones',
                'alergias'            => 'Ninguna',
                'rh'               => 'O+',
                'eps'              => 'SURA EPS',
                'arl'              => 'SURA',
                'fondo_pensiones'  => 'PROTECCION',
                'caja_compensacion'=> 'COMFAMA',
                'licencia_carro'       => 'B1',
                'licencia_carro_vence' => '2028-06-14',
                'licencia_moto'        => null,
                'licencia_moto_vence'  => null,
                'tiene_cert_alturas'   => false,
                'cert_alturas_vence'   => null,
                'estado_empleado' => 'Activo',
                'codigo_directv'  => 'DTV-002',
                'empresa_id'      => $empServMercadeo,
                'comentarios'     => 'Analista administrativo área comercial.',
                'cargo'            => 'ANALISTA ADMINISTRATIVO',
                'tipo_funcionario' => 'ADMINISTRATIVO',
                'tipo_vinculacion' => 'Empleado directo',
                'cuenta_bancaria'  => '987654321001',
                'tipo_cuenta'      => 'Ahorros',
                'banco'            => 'DAVIVIENDA',
                'contacto_emergencia_nombre'     => 'Laura Morales',
                'contacto_emergencia_telefono'   => '3156789012',
                'contacto_emergencia_parentesco' => 'Madre',
            ],
            [
                'name'     => 'Ana Maria Lopez Restrepo',
                'email'    => 'ana.lopez@empresa.com',
                'password' => Hash::make('Password123'),
                'rol'      => 'consultor',
                'activo'   => true,
                'cedula'              => '43876543',
                'apellidos'           => 'Lopez Restrepo',
                'nombres'             => 'Ana Maria',
                'sede'                => 'Pereira',
                'fecha_nacimiento'    => '1991-03-08',
                'lugar_nacimiento'    => 'Pereira',
                'raza'                => 'Mestizo',
                'genero'              => 'Femenino',
                'estado_civil'        => 'Casado/a',
                'nivel_escolaridad'   => 'Profesional',
                'direccion_residencia'=> 'Carrera 14 # 20-55 Apt 301',
                'movil'               => '3117654321',
                'estrato'             => '3',
                'barrio'              => 'Cuba',
                'numero_hijos'        => 1,
                'ingresos'            => 2800000,
                'observaciones_medicas' => 'Sin observaciones',
                'alergias'            => 'Polen',
                'rh'               => 'A+',
                'eps'              => 'COMFAMILIAR RISARALDA',
                'arl'              => 'POSITIVA',
                'fondo_pensiones'  => 'PORVENIR',
                'caja_compensacion'=> 'COMFAMILIAR RISARALDA',
                'licencia_carro'       => null,
                'licencia_carro_vence' => null,
                'licencia_moto'        => null,
                'licencia_moto_vence'  => null,
                'tiene_cert_alturas'   => false,
                'cert_alturas_vence'   => null,
                'estado_empleado' => 'Activo',
                'codigo_directv'  => 'DTV-003',
                'empresa_id'      => $empServMercadeo,
                'comentarios'     => 'Analista de talento humano y bienestar.',
                'cargo'            => 'ANALISTA DE TALENTO HUMANO',
                'tipo_funcionario' => 'ADMINISTRATIVO',
                'tipo_vinculacion' => 'Empleado directo',
                'cuenta_bancaria'  => '456789012345',
                'tipo_cuenta'      => 'Ahorros',
                'banco'            => 'BANCOLOMBIA',
                'contacto_emergencia_nombre'     => 'Jorge López',
                'contacto_emergencia_telefono'   => '3001234567',
                'contacto_emergencia_parentesco' => 'Esposo',
            ],
            [
                'name'     => 'Carlos Alberto Ospina Vargas',
                'email'    => 'carlos.ospina@empresa.com',
                'password' => Hash::make('Password123'),
                'rol'      => 'consultor',
                'activo'   => true,
                'cedula'              => '71234567',
                'apellidos'           => 'Ospina Vargas',
                'nombres'             => 'Carlos Alberto',
                'sede'                => 'Medellín',
                'fecha_nacimiento'    => '1988-11-20',
                'lugar_nacimiento'    => 'Medellín',
                'raza'                => 'Mestizo',
                'genero'              => 'Masculino',
                'estado_civil'        => 'Casado/a',
                'nivel_escolaridad'   => 'Profesional',
                'direccion_residencia'=> 'Carrera 80 # 47-50 Apt 202',
                'movil'               => '3209876543',
                'estrato'             => '4',
                'barrio'              => 'La Floresta',
                'numero_hijos'        => 2,
                'ingresos'            => 4500000,
                'observaciones_medicas' => 'Sin observaciones',
                'alergias'            => 'Ninguna',
                'rh'               => 'B+',
                'eps'              => 'SURA EPS',
                'arl'              => 'SURA',
                'fondo_pensiones'  => 'COLFONDOS',
                'caja_compensacion'=> 'COMFAMA',
                'licencia_carro'       => 'B1',
                'licencia_carro_vence' => '2027-11-20',
                'licencia_moto'        => null,
                'licencia_moto_vence'  => null,
                'tiene_cert_alturas'   => false,
                'cert_alturas_vence'   => null,
                'estado_empleado' => 'Activo',
                'codigo_directv'  => 'DTV-004',
                'empresa_id'      => $empServimercadeo,
                'comentarios'     => 'Coordinador comercial zona Antioquia.',
                'cargo'            => 'COORDINADOR COMERCIAL',
                'tipo_funcionario' => 'COMERCIAL',
                'tipo_vinculacion' => 'Empleado directo',
                'cuenta_bancaria'  => '789012345678',
                'tipo_cuenta'      => 'Corriente',
                'banco'            => 'BBVA',
                'jefe_inmediato'   => 'SIMON GALLEGO MORALES',
                'contacto_emergencia_nombre'     => 'Patricia Vargas',
                'contacto_emergencia_telefono'   => '3042345678',
                'contacto_emergencia_parentesco' => 'Madre',
            ],
            [
                'name'     => 'Diana Marcela Martinez Rios',
                'email'    => 'diana.martinez@empresa.com',
                'password' => Hash::make('Password123'),
                'rol'      => 'consultor',
                'activo'   => true,
                'cedula'              => '52345678',
                'apellidos'           => 'Martinez Rios',
                'nombres'             => 'Diana Marcela',
                'sede'                => 'Cali',
                'fecha_nacimiento'    => '1993-07-15',
                'lugar_nacimiento'    => 'Cali',
                'raza'                => 'Mestizo',
                'genero'              => 'Femenino',
                'estado_civil'        => 'Soltero/a',
                'nivel_escolaridad'   => 'Tecnóloga',
                'direccion_residencia'=> 'Calle 47 # 5A-34 B/La Flora',
                'movil'               => '3165432109',
                'estrato'             => '3',
                'barrio'              => 'La Flora',
                'numero_hijos'        => 0,
                'ingresos'            => 2600000,
                'observaciones_medicas' => 'Sin observaciones',
                'alergias'            => 'Ninguna',
                'rh'               => 'O-',
                'eps'              => 'NUEVA E.P.S',
                'arl'              => 'POSITIVA',
                'fondo_pensiones'  => 'COLPENSIONES',
                'caja_compensacion'=> 'COMFANDI',
                'licencia_carro'       => null,
                'licencia_carro_vence' => null,
                'licencia_moto'        => 'A2',
                'licencia_moto_vence'  => '2026-07-15',
                'tiene_cert_alturas'   => false,
                'cert_alturas_vence'   => null,
                'estado_empleado' => 'Activo',
                'codigo_directv'  => 'DTV-005',
                'empresa_id'      => $empServimercadeo,
                'comentarios'     => 'Supervisora de operaciones zona Valle.',
                'cargo'            => 'SUPERVISOR DE OPERACIONES',
                'tipo_funcionario' => 'OPERATIVO',
                'tipo_vinculacion' => 'Empleado directo',
                'cuenta_bancaria'  => '234567890123',
                'tipo_cuenta'      => 'Ahorros',
                'banco'            => 'DAVIVIENDA',
                'contacto_emergencia_nombre'     => 'Rosa Ríos',
                'contacto_emergencia_telefono'   => '3183456789',
                'contacto_emergencia_parentesco' => 'Madre',
            ],
            [
                'name'     => 'Jorge Emilio Varon Castillo',
                'email'    => 'jorge.varon@empresa.com',
                'password' => Hash::make('Password123'),
                'rol'      => 'consultor',
                'activo'   => true,
                'cedula'              => '94567890',
                'apellidos'           => 'Varon Castillo',
                'nombres'             => 'Jorge Emilio',
                'sede'                => 'Pereira',
                'fecha_nacimiento'    => '1985-02-28',
                'lugar_nacimiento'    => 'Pereira',
                'raza'                => 'Mestizo',
                'genero'              => 'Masculino',
                'estado_civil'        => 'Casado/a',
                'nivel_escolaridad'   => 'Profesional',
                'direccion_residencia'=> 'Av. Circunvalar # 10-32',
                'movil'               => '3196543210',
                'estrato'             => '4',
                'barrio'              => 'El Poblado',
                'numero_hijos'        => 3,
                'ingresos'            => 5800000,
                'observaciones_medicas' => 'Sin observaciones',
                'alergias'            => 'Ninguna',
                'rh'               => 'A+',
                'eps'              => 'SURA EPS',
                'arl'              => 'SURA',
                'fondo_pensiones'  => 'PROTECCION',
                'caja_compensacion'=> 'COMFAMILIAR RISARALDA',
                'licencia_carro'       => 'B1',
                'licencia_carro_vence' => '2029-02-28',
                'licencia_moto'        => null,
                'licencia_moto_vence'  => null,
                'tiene_cert_alturas'   => true,
                'cert_alturas_vence'   => '2027-03-01',
                'estado_empleado' => 'Activo',
                'codigo_directv'  => 'DTV-006',
                'empresa_id'      => $empServMercadeo,
                'comentarios'     => 'Gerente de procesos administrativos y operativos.',
                'cargo'            => 'GERENTE DE PROCESOS ADMINISTRATIVOS',
                'tipo_funcionario' => 'ADMINISTRATIVO',
                'tipo_vinculacion' => 'Empleado directo',
                'cuenta_bancaria'  => '567890123456',
                'tipo_cuenta'      => 'Ahorros',
                'banco'            => 'BANCOLOMBIA',
                'contacto_emergencia_nombre'     => 'Carmen Castillo',
                'contacto_emergencia_telefono'   => '3024567890',
                'contacto_emergencia_parentesco' => 'Esposa',
            ],
        ];

        $upper = fn($v) => $v !== null ? mb_strtoupper($v, 'UTF-8') : null;
        $upperFields = ['nombres', 'apellidos', 'name', 'cargo', 'fondo_pensiones', 'arl', 'tipo_funcionario', 'eps', 'caja_compensacion', 'banco'];

        foreach ($empleados as $data) {
            foreach ($upperFields as $campo) {
                if (isset($data[$campo])) {
                    $data[$campo] = $upper($data[$campo]);
                }
            }

            DB::table('users')->insertOrIgnore(array_merge($data, [
                'created_at' => now(),
                'updated_at' => now(),
            ]));
        }

        $this->command->info('✓ ' . count($empleados) . ' empleados insertados');
    }
}
